### ISSUE TITLE
[Features] Show menu in "New note"

### ISSUE THREAD

**Issue by SeaPants** [jmerle/inkdrop-tray#1]
Thank you for a good job.

if it is technically possible, I would be happy if there was a function to add a new note in the context menu.

**Comment by jmerle** [comment]
Implemented in https://github.com/jmerle/inkdrop-tray/commit/bdbfb6425383609fd0de70eb94e389dd43762a95, released in [v1.2.0](https://github.com/jmerle/inkdrop-tray/releases/tag/v1.2.0).
