### ISSUE TITLE
Support v5.5.0

### ISSUE THREAD

**Issue by craftzdog** [jmerle/inkdrop-tray#11]
Hi jmerle! Thanks for creating the great plugin.
As of v5.5.0, `require('electron').remote` is no longer available.
You can use `require('@electron/remote')` instead.
Could you update it?

**Comment by jmerle** [comment]
Fixed in a462082d4c4fb702facbd2ef7cf246d401aebf27, released in [v1.4.1](https://github.com/jmerle/inkdrop-tray/releases/tag/v1.4.1).
