### ISSUE TITLE
Minimize to tray on close

### ISSUE THREAD

**Issue by piowyr** [jmerle/inkdrop-tray#14]
Hello jmerle! Great plugin!
Is it possible to add the option to minimize to tray on close?

**Comment by jmerle** [comment]
I'm not sure yet whether this is something an Inkdrop plugin is able to do, see [this forum topic](https://forum.inkdrop.app/t/detect-and-cancel-inkdrop-exiting-from-plugin/3233) for more information.

**Comment by jmerle** [comment]
The creator of Inkdrop responded [here](https://forum.inkdrop.app/t/detect-and-cancel-inkdrop-exiting-from-plugin/3233/2), unfortunately this is not something an Inkdrop plugin is able to do.
