### ISSUE TITLE
Monochrome tray icon (configurable)

### ISSUE THREAD

**Issue by akalinkin** [jmerle/inkdrop-tray#9]
It would be great to have a setting to change tray icon look and feel.
In some setups monochrome icons will look more organic.

- add setting `use monochrome icon`: [true|false]
- if true -> use monochrome icon
- else -> use regular icon

**Comment by jmerle** [comment]
Sorry for the delay. Implemented in https://github.com/jmerle/inkdrop-tray/commit/b25d1dc226affd18bab5fe9331618264ec2977d4, released in v1.4.0.
